mittwald/kube-httpcache

README.md
Fixes #13, credits to @dealancer
=> Adjust README to correctly set backend namespace and service

README.md, controller/run.go, controller/types.go, controller/watch.go, flags.go, main.go, watcher/endpoints.go, watcher/endpoints_watch.go, watcher/types.go
This PR fixes https://github.com/mittwald/kube-httpcache/issues/7
=> Allow for watching and templating the kube-httpcache service

.gitignore, .goreleaser.yml, .travis.yml, Dockerfile, go.mod
=> use goreleaser

README.md
=> Fix some documentation bugs

cmd/kube-httpcache/internal/flags.go, cmd/kube-httpcache/main.go, pkg/controller/run.go, pkg/controller/types.go, pkg/readiness/server.go
=> Implement readiness probe

pkg/signaller/run.go
=> Fix race condition in signaller component

pkg/watcher/endpoints_watch.go
=> Fix panic when no backend Pod is ready

cmd/kube-httpcache/internal/flags.go, cmd/kube-httpcache/main.go, pkg/controller/run.go, pkg/controller/types.go
Some other minor changes are removing of trailing spaces.
=> Add support of a Varnish "-n" option - setting a working dir

chart/templates/deployment.yaml, chart/templates/statefulset.yaml, chart/values.yaml
=> added helm option to disable backend-watch

build/package/docker/Dockerfile, chart/templates/deployment.yaml, chart/templates/service.yaml, chart/templates/servicemonitor.yaml, chart/templates/statefulset.yaml, chart/values.yaml
Any feedback review is welcome, probably there are some better / other approaches for some parts.
This closes #62
=> added prometheus exporter to image and helm chart

README.md
=> Explain how to build Docker image in README

pkg/watcher/template_watch.go
i'll easily be the first to say that my golang skills are very severely lacking, so any feedback is more than welcome
i pretty much lifted this change verbatim from the comment left by @timkante, pulled from the fsnotify docs
=> Explicitly check for write events in fsnotify watcher (#81)

chart/values.yaml
This PR intends to fix a very small typo in the default values of the chart.
=> Helm: Fix default values documentation typo.

pkg/controller/watch.go, pkg/signaller/run.go, pkg/signaller/types.go
This PR fixes a bunch of logging typos in the `pkg/` subdirectory 🙂 
No functional impact expected, just a readability improvement.
Best regards
=> pkg: Fix logging typos.

README.md
=> Fix incorrect port definitions in README

README.md
Fix ascii overview diagram "Ingress -> Varnish -> Application" in first section "## How it works" of README.md
=> Fix ascii diagram in README.md

chart/templates/deployment.yaml, chart/templates/statefulset.yaml, chart/values.yaml
closes #149 
This avoids having to build and maintain a Docker image with custom vmods - thanks!
=> Add extra env vars and envFrom

build/package/docker/Dockerfile
Fixes https://github.com/mittwald/kube-httpcache/issues/106
=> add varnish exporter builder

chart/templates/pdb.yaml
=> add PodDisruptionBudget

chart/templates/deployment.yaml, chart/templates/statefulset.yaml, chart/values.yaml
Allow to specify backendService via the tpl function, when used as an HELM dependency
=> use tpl in backendService
