mittwald/kube-httpcache

- cmd/kube-httpcache/internal/flags.go
- cmd/kube-httpcache/main.go
- pkg/controller/run.go
- pkg/controller/types.go
In the current version, it's not possible to start varnish with additional run parameter (https://varnish-cache.org/docs/6.0/reference/varnishd.html#list-of-parameters).
This PR add this possibility with a simple generic approach.
Tested on a local minikube.
> Add additional varnish run parameter

- .github/workflows/stale.yml
Exempt issue names apparently need to be specified with URL encoding (see actions/stale#98).
> Do not mark "help wanted" issues as stale

- README.md
- pkg/controller/types.go
At the Varnish configuration template the {{ .Env.ENVVAR }} is changed to the value of the environment variable. If the environment variable doesn't exist, this crashes.
> Added the environment variable parsing for the configuration template

- README.md
- chart/templates/NOTES.txt
This PR adds a warning note to the `NOTES.txt` output in certain edge cases.
This is a follow-up to a discussion in https://github.com/mittwald/kube-httpcache/pull/51#discussion_r580575588.
> Improve Helm chart documentation, and add warning to NOTES.txt in edge cases

- pkg/signaller/run.go
A memory leak is caused by an unclosed response body when a high volume of incoming PURGE requests is propagated among instances of a Varnish cluster.
Before changes:
```
1 root      20   0   20.7g  20.0g  15544 S   0.0  35.4 186:05.55 kube-httpcache
22 varnish   20   0   18564   4488   3800 S   0.0   0.0   0:33.54 varnishd
34 vcache    20   0 4873816   3.0g  85248 S   0.0   5.3 450:00.98 cache-main
```
After changes:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
35 vcache    20   0 2760588   1.4g  86308 S 640.0   2.6 128:44.85 cache-main
1 root      20   0  730008  27248  15316 S 126.7   0.0  28:55.55 kube-httpcache
23 varnish   20   0   18568   5544   4888 S   0.0   0.0   0:00.75 varnishd
```
> Fix a memory leak in Signaller.ProcessSignalQueue due to an unclosed response body

- chart/templates/deployment.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
This options has been useful for the way we have being using this 
project
- add helm option to change the frontend service name
- add helm option to set varnish container lifecycle options
- add helm option to add extracontainers to the pod
- add helm option to set the pod termination grace period
> Add extra options to helm chart

- chart/templates/deployment.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
In cases in which we don't use frontend-watch we need an option to disable this.
Imho it's also not possible to use frontend-watch and readinessProbes at the same time.
> added option to disable frontendwatch to helm chart

- chart/templates/deployment.yaml
- chart/templates/secret.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
This PR adds an option to use an existing secret for the admin credentials..
This comes in need to fix this issue #56 
I'm really sure why is needed, in this comment https://github.com/mittwald/kube-httpcache/pull/51#discussion_r547112352 you mentioned that if the secret is updated it shouldn't be used until the pods are restarted.
> Add option to use a user provided secret for the admin credentials

- chart/Chart.yaml
- chart/values.yaml
`cache.template` does not seem to be used anywhere. The filename of the rendered VCL is hard-coded in the constructor of [`VarnishController`](https://github.com/mittwald/kube-httpcache/blob/master/pkg/controller/types.go#L89)
> Remove unused config parameter

- chart/templates/deployment.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
This PR intends to add the support for K8s `topologySpreadConstraints` mechanism.
The purpose of this concept is to control how Pods are being scheduled in K8s clusters ([official documentation here](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/))
- Support proposed to `Deployment` as well as `StatefulSet` resources
- Render has been tested through `helm lint` & `helm template`
- Suggested commented configuration suggests HA (1 instance per host + cross-AZ repartition as a best-effort)
- The feature is supported as of kubernetes 1.19
Thanks for open-sourcing this awesome project ! 🙂
> Helm: add support for topologySpreadConstraints.

- README.md
2 parts of the README mention the ACLs.
As a lot of newcomers to FOSS projects tends to follow documentations insights  & copy/paste examples to build a simple configuration to start with, I believe it's worth reducing the chances they face a broken configuration.
**TL;DR:** This PR ensures the examples are following the same ACL naming conventions 🙂
> README: Align ACL examples content.

- chart/templates/statefulset.yaml
The deployment allows changing the transient storage - add same functionality to StatefulSet
https://github.com/mittwald/kube-httpcache/blob/a14f157b3c496ef403a424e457a5060d0b8e5c92/chart/templates/deployment.yaml#L78-L80
> Chart: Allow changing transient storage on STS

- chart/templates/deployment.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
- cmd/kube-httpcache/internal/flags.go
The port 8080 is a "standard" HTTP port for applications running inside a private infrastructure. As the default HTTP port (80) is a system port, it is not possible to restrain permissions through the securityContext and drop rootUser out-of-the-box. This will result in a permission error while trying to create a socket on port 80.
This commit intends to fix this and make the application of the securityContext
(required in most if not every production clusters) a lot more simple.
⚠️ This is a breaking change from previous versions
```bash
k logs -f kube-httpcache-7dd77678c9-bcsxb
I0901 17:33:33.859847       1 main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:true …
```
> Varnish: Change default port from 80 to 8080.

- cmd/kube-httpcache/internal/flags.go
- cmd/kube-httpcache/main.go
- pkg/signaller/run.go
- pkg/signaller/types.go
This commit introduces additional options for tweaking Signaller HTTP-client:
* adjusting MaxConnsPerHost, MaxIdleConns, MaxIdleConnsPerHost on
http.Transport fields if they are different from the default value of
a corresponding command-line argument, but with the possibility to set
them to 0, because 0 is a valid value for them;
* setting a timeout on Signaller HTTP-requests towards upstream;
Also, this commit adds draining of a response body from Signaler's
upstream for improving connection reuse.
> Make Signaller HTTP-client more configurable

- chart/templates/ingress.yaml
- chart/values.yaml
New ingress supports different versions of kubernetes and allows to set className
> Make ingress.yaml kube version agnostic and add className param

- build/package/docker/Dockerfile
- build/package/docker/GoReleaser.Dockerfile
Super simple PR that bumps the varnish_exporter version and helps with part of #81
> Dockerfiles: bump exporter version

- chart/templates/servicemonitor.yaml
- chart/values.yaml
* Allows control of the scrape interval + timeout
* Allows setting of extra labels on the ServiceMonitor object
A breaking-ish change as the `serviceMonitor` config key is no longer a bool.
I needed this as my prometheus deployment is expecting ServiceMonitors with the specific release label.
eg. 
``` yaml
serviceMonitor:
additionalLabels:
release: kube-prometheus-stack
```
> Helm: Allow label customization for servicemonitor

- go.mod
- go.sum
- pkg/controller/watch.go
This PR fixes #81.
03344103867acc8c639c4f2be11d36f3df8c54ac fixes the varnish exporter resource consumption issues by using `reload_<timestamp` as a vcl name
03344103867acc8c639c4f2be11d36f3df8c54ac is an update to #95, it attempts to keep at most `max_vcl` VCLs available in memory, discarding the rest. The default value in varnish is 100, a different value can be set via `-varnish-additional-parameters=max_vcl=10`
> Fix resource consumption issues

- pkg/controller/types.go
- pkg/controller/watch.go
This PR removes the `secret` variable from the controller and instead reads the secret file before each authentication attempt.
Fixes #56 by ensuring that the correct password is used for all reloads.
Relevant varnish docs: https://github.com/varnishcache/varnish-cache/blob/606977bbfb624ead38e9c8648beac0b3906a4294/doc/sphinx/users-guide/run_security.rst#cli-interface-authentication, specifically: 
> You can change the contents of the secret file while varnishd runs, it is read every time a CLI connection is authenticated.
> Read secret file before each authentication attempt

- build/package/docker/Dockerfile
- build/package/docker/GoReleaser.Dockerfile
**PR related to #156** 
Due to the EOL of `debian:stretch` i made a switch to `debian:bullseye`.
This PR is **untested**. 
Docker-Build works without errors but **functionality of varnish etc. was not tested.**
(It's friday EOB, we'll check it next week)
**"Why do you create a untested PR?"**
I created this PR because we had issues with connection to the stretch package-repos.
Seems like they were removed after a grace period.
But even this untested PR might help someone with this issue.
Tests of voluntaries are appreciated.
**EDIT1**: It's BOB and first tests seem to be promising.
Added a change pinning varnish to 6.0.11 because 6.5.* would be used otherwise.
**EDIT2**: It's already deployed to our production environment and no issues occurred so far.
(It's a portal with many thousands …
> Upgrade to debian:bullseye-slim 

- chart/templates/service.yaml
- chart/values.yaml
This adds configurable annotations to the service. This is sometimes necessary in cloud environments such as google to configure a backendconfig for health checks and other load balancing features:
```
service:
type: ClusterIP
port: 80
target: 80
annotations:
cloud.google.com/backend-config: '{"default": "some-backendconfig"}'
cloud.google.com/neg: '{"ingress": true}'
```
> Add configurable annotations to service
